name: Deploy Supported Emoji

on:
  push:
    branches:
      - main
    paths:
      - "supported-emoji/**"
  workflow_dispatch:

jobs:
  job:
    name: Deploy Supported Emoji
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“¦
        uses: actions/checkout@v6

      - name: Configure AWS Credentials ğŸ”‘
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform ğŸ—
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.10.2
          terraform_wrapper: false # Necessary to access output

      - name: Terraform Init âœ¨
        id: init
        run: terraform init -upgrade
        working-directory: ./terraform

      - name: Save Lambda function name to Environment Variables ğŸ’¾
        run: echo "LAMBDA_FUNCTION_NAME=$(terraform output -raw supported_emoji_lambda_function)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Setup Node ğŸ—
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Install packages ğŸ“€
        run: npm ci
        working-directory: ./supported-emoji

      - name: Create Deployment Package ğŸ
        run: zip -r lambda.zip .
        working-directory: ./supported-emoji

      - name: Deploy Lambda Function ğŸš€
        env:
          LAMBDA_FUNCTION_NAME: ${{ env.LAMBDA_FUNCTION_NAME }}
        run: aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda.zip
        working-directory: ./supported-emoji
